import type { FormatSpec, FormatCategory } from "./types";

const PRINT_DPI = 300;

function printPx(cm: number, dpi = PRINT_DPI): number {
  return Math.round((cm / 2.54) * dpi);
}

// ─── Print ────────────────────────────────────────────────────────────────────

const PRINT: FormatSpec[] = [
  {
    id: "print_a5_portrait",
    name: "A5 Portrait",
    description: "ISO A5 — compact souvenir or postcard",
    category: "print",
    unit: "cm",
    width: 14.8,
    height: 21,
    pixelWidth: printPx(14.8),
    pixelHeight: printPx(21),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_a4_portrait",
    name: "A4 Portrait",
    description: "ISO A4 — standard print poster",
    category: "print",
    unit: "cm",
    width: 21,
    height: 29.7,
    pixelWidth: printPx(21),
    pixelHeight: printPx(29.7),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_a3_portrait",
    name: "A3 Portrait",
    description: "ISO A3 — large wall poster",
    category: "print",
    unit: "cm",
    width: 29.7,
    height: 42,
    pixelWidth: printPx(29.7),
    pixelHeight: printPx(42),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_a2_portrait",
    name: "A2 Portrait",
    description: "ISO A2 — gallery-scale print",
    category: "print",
    unit: "cm",
    width: 42,
    height: 59.4,
    pixelWidth: printPx(42),
    pixelHeight: printPx(59.4),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_travel_s",
    name: "Travel Poster S",
    description: "30×45 cm — classic souvenir poster ratio",
    category: "print",
    unit: "cm",
    width: 30,
    height: 45,
    pixelWidth: printPx(30),
    pixelHeight: printPx(45),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_travel_m",
    name: "Travel Poster M",
    description: "40×60 cm — mid-size framed poster",
    category: "print",
    unit: "cm",
    width: 40,
    height: 60,
    pixelWidth: printPx(40),
    pixelHeight: printPx(60),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_travel_l",
    name: "Travel Poster L",
    description: "50×70 cm — large framed wall art",
    category: "print",
    unit: "cm",
    width: 50,
    height: 70,
    pixelWidth: printPx(50),
    pixelHeight: printPx(70),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_travel_xl",
    name: "Travel Poster XL",
    description: "70×100 cm — exhibition-scale print",
    category: "print",
    unit: "cm",
    width: 70,
    height: 100,
    pixelWidth: printPx(70),
    pixelHeight: printPx(100),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
  {
    id: "print_square_30",
    name: "Square Print 30cm",
    description: "30×30 cm — square framed print",
    category: "print",
    unit: "cm",
    width: 30,
    height: 30,
    pixelWidth: printPx(30),
    pixelHeight: printPx(30),
    dpi: PRINT_DPI,
    defaultFormat: "png",
  },
  {
    id: "print_letter_portrait",
    name: "US Letter Portrait",
    description: "8.5×11 in — North American standard",
    category: "print",
    unit: "cm",
    width: 21.59,
    height: 27.94,
    pixelWidth: printPx(21.59),
    pixelHeight: printPx(27.94),
    dpi: PRINT_DPI,
    defaultFormat: "pdf",
  },
];

// ─── Social ───────────────────────────────────────────────────────────────────

const SOCIAL: FormatSpec[] = [
  // Instagram
  {
    id: "social_ig_square",
    name: "Instagram Square",
    description: "1:1 — Instagram feed square post",
    category: "social",
    unit: "px",
    width: 1080,
    height: 1080,
    pixelWidth: 1080,
    pixelHeight: 1080,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_ig_portrait",
    name: "Instagram Portrait",
    description: "4:5 — Instagram feed portrait (most reach)",
    category: "social",
    unit: "px",
    width: 1080,
    height: 1350,
    pixelWidth: 1080,
    pixelHeight: 1350,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_ig_landscape",
    name: "Instagram Landscape",
    description: "1.91:1 — Instagram feed landscape",
    category: "social",
    unit: "px",
    width: 1080,
    height: 566,
    pixelWidth: 1080,
    pixelHeight: 566,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // Facebook
  {
    id: "social_fb_post",
    name: "Facebook Post",
    description: "1.91:1 — Facebook feed link/image post",
    category: "social",
    unit: "px",
    width: 1200,
    height: 630,
    pixelWidth: 1200,
    pixelHeight: 630,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_fb_cover",
    name: "Facebook Cover",
    description: "2.7:1 — Facebook profile/page cover",
    category: "social",
    unit: "px",
    width: 851,
    height: 315,
    pixelWidth: 851,
    pixelHeight: 315,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_fb_event_cover",
    name: "Facebook Event Cover",
    description: "1.91:1 — Facebook event header",
    category: "social",
    unit: "px",
    width: 1920,
    height: 1005,
    pixelWidth: 1920,
    pixelHeight: 1005,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // Twitter / X
  {
    id: "social_x_post",
    name: "X / Twitter Post",
    description: "16:9 — X (Twitter) in-feed image post",
    category: "social",
    unit: "px",
    width: 1200,
    height: 675,
    pixelWidth: 1200,
    pixelHeight: 675,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_x_header",
    name: "X / Twitter Header",
    description: "3:1 — X (Twitter) profile header banner",
    category: "social",
    unit: "px",
    width: 1500,
    height: 500,
    pixelWidth: 1500,
    pixelHeight: 500,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // LinkedIn
  {
    id: "social_linkedin_post",
    name: "LinkedIn Post",
    description: "1.91:1 — LinkedIn image post",
    category: "social",
    unit: "px",
    width: 1200,
    height: 627,
    pixelWidth: 1200,
    pixelHeight: 627,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "social_linkedin_cover",
    name: "LinkedIn Cover",
    description: "4:1 — LinkedIn profile cover banner",
    category: "social",
    unit: "px",
    width: 1584,
    height: 396,
    pixelWidth: 1584,
    pixelHeight: 396,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // Pinterest
  {
    id: "social_pinterest_pin",
    name: "Pinterest Pin",
    description: "2:3 — Pinterest standard pin",
    category: "social",
    unit: "px",
    width: 1000,
    height: 1500,
    pixelWidth: 1000,
    pixelHeight: 1500,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // YouTube
  {
    id: "social_youtube_thumbnail",
    name: "YouTube Thumbnail",
    description: "16:9 — YouTube video thumbnail",
    category: "social",
    unit: "px",
    width: 1280,
    height: 720,
    pixelWidth: 1280,
    pixelHeight: 720,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // Threads
  {
    id: "social_threads_portrait",
    name: "Threads Portrait",
    description: "4:5 — Threads portrait image post",
    category: "social",
    unit: "px",
    width: 1080,
    height: 1350,
    pixelWidth: 1080,
    pixelHeight: 1350,
    dpi: 96,
    defaultFormat: "jpg",
  },
  // Reddit
  {
    id: "social_reddit_post",
    name: "Reddit Post",
    description: "16:9 — Reddit widescreen image post",
    category: "social",
    unit: "px",
    width: 1200,
    height: 675,
    pixelWidth: 1200,
    pixelHeight: 675,
    dpi: 96,
    defaultFormat: "jpg",
  },
];

// ─── Stories (9:16 vertical) ──────────────────────────────────────────────────

const STORIES: FormatSpec[] = [
  {
    id: "stories_ig",
    name: "Instagram Story",
    description: "9:16 — Instagram Story & Reels cover",
    category: "stories",
    unit: "px",
    width: 1080,
    height: 1920,
    pixelWidth: 1080,
    pixelHeight: 1920,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "stories_fb",
    name: "Facebook Story",
    description: "9:16 — Facebook Story",
    category: "stories",
    unit: "px",
    width: 1080,
    height: 1920,
    pixelWidth: 1080,
    pixelHeight: 1920,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "stories_tiktok",
    name: "TikTok",
    description: "9:16 — TikTok video cover / photo post",
    category: "stories",
    unit: "px",
    width: 1080,
    height: 1920,
    pixelWidth: 1080,
    pixelHeight: 1920,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "stories_snapchat",
    name: "Snapchat Story",
    description: "9:16 — Snapchat full-screen snap",
    category: "stories",
    unit: "px",
    width: 1080,
    height: 1920,
    pixelWidth: 1080,
    pixelHeight: 1920,
    dpi: 96,
    defaultFormat: "jpg",
  },
  {
    id: "stories_whatsapp",
    name: "WhatsApp Status",
    description: "9:16 — WhatsApp Status full-screen",
    category: "stories",
    unit: "px",
    width: 1080,
    height: 1920,
    pixelWidth: 1080,
    pixelHeight: 1920,
    dpi: 96,
    defaultFormat: "jpg",
  },
];

// ─── Wallpaper ────────────────────────────────────────────────────────────────

const WALLPAPER: FormatSpec[] = [
  {
    id: "wallpaper_fhd",
    name: "Desktop Full HD",
    description: "1920×1080 — 16:9 desktop wallpaper",
    category: "wallpaper",
    unit: "px",
    width: 1920,
    height: 1080,
    pixelWidth: 1920,
    pixelHeight: 1080,
    dpi: 96,
    defaultFormat: "png",
  },
  {
    id: "wallpaper_4k",
    name: "Desktop 4K",
    description: "3840×2160 — 4K UHD desktop wallpaper",
    category: "wallpaper",
    unit: "px",
    width: 3840,
    height: 2160,
    pixelWidth: 3840,
    pixelHeight: 2160,
    dpi: 96,
    defaultFormat: "png",
  },
  {
    id: "wallpaper_ultrawide",
    name: "Ultrawide",
    description: "3440×1440 — 21:9 ultrawide monitor",
    category: "wallpaper",
    unit: "px",
    width: 3440,
    height: 1440,
    pixelWidth: 3440,
    pixelHeight: 1440,
    dpi: 96,
    defaultFormat: "png",
  },
  {
    id: "wallpaper_iphone",
    name: "iPhone",
    description: "1290×2796 — iPhone 15 Pro Max wallpaper",
    category: "wallpaper",
    unit: "px",
    width: 1290,
    height: 2796,
    pixelWidth: 1290,
    pixelHeight: 2796,
    dpi: 96,
    defaultFormat: "png",
  },
  {
    id: "wallpaper_android",
    name: "Android",
    description: "1440×3120 — Samsung Galaxy S24 Ultra wallpaper",
    category: "wallpaper",
    unit: "px",
    width: 1440,
    height: 3120,
    pixelWidth: 1440,
    pixelHeight: 3120,
    dpi: 96,
    defaultFormat: "png",
  },
  {
    id: "wallpaper_ipad",
    name: "iPad Pro 12.9\"",
    description: "2048×2732 — iPad Pro 12.9-inch wallpaper",
    category: "wallpaper",
    unit: "px",
    width: 2048,
    height: 2732,
    pixelWidth: 2048,
    pixelHeight: 2732,
    dpi: 96,
    defaultFormat: "png",
  },
];

// ─── Web ──────────────────────────────────────────────────────────────────────

const WEB: FormatSpec[] = [
  {
    id: "web_og_card",
    name: "OG / Share Card",
    description: "1200×630 — Open Graph card for link previews",
    category: "web",
    unit: "px",
    width: 1200,
    height: 630,
    pixelWidth: 1200,
    pixelHeight: 630,
    dpi: 96,
    defaultFormat: "webp",
  },
  {
    id: "web_hero",
    name: "Hero Banner",
    description: "1440×600 — Wide hero section for landing pages",
    category: "web",
    unit: "px",
    width: 1440,
    height: 600,
    pixelWidth: 1440,
    pixelHeight: 600,
    dpi: 96,
    defaultFormat: "webp",
  },
  {
    id: "web_blog_cover",
    name: "Blog Cover",
    description: "1200×628 — Blog post featured image",
    category: "web",
    unit: "px",
    width: 1200,
    height: 628,
    pixelWidth: 1200,
    pixelHeight: 628,
    dpi: 96,
    defaultFormat: "webp",
  },
  {
    id: "web_email_header",
    name: "Email Header",
    description: "600×200 — Email newsletter header",
    category: "web",
    unit: "px",
    width: 600,
    height: 200,
    pixelWidth: 600,
    pixelHeight: 200,
    dpi: 96,
    defaultFormat: "jpg",
  },
];

// ─── Registry ─────────────────────────────────────────────────────────────────

export const ALL_FORMATS: FormatSpec[] = [
  ...PRINT,
  ...SOCIAL,
  ...STORIES,
  ...WALLPAPER,
  ...WEB,
];

export const FORMAT_CATEGORIES: { id: FormatCategory; name: string }[] = [
  { id: "print", name: "Print" },
  { id: "social", name: "Social Media" },
  { id: "stories", name: "Stories & Reels" },
  { id: "wallpaper", name: "Wallpaper" },
  { id: "web", name: "Web" },
];

export function getFormatsByCategory(category: FormatCategory): FormatSpec[] {
  return ALL_FORMATS.filter((f) => f.category === category);
}

export function getFormatById(id: string): FormatSpec | undefined {
  return ALL_FORMATS.find((f) => f.id === id);
}
