/**
 * Pre-baked MapLibre style specifications — one per theme.
 *
 * Generated by:  npm run styles:generate
 * Re-run after changing theme colors or maplibreStyle.ts.
 *
 * Usage:
 *   import { getLocalStyle } from "@/map-styles";
 *   map.setStyle(getLocalStyle("midnight_blue"));
 *
 * Or load by URL when served statically:
 *   map.setStyle("/map-styles/midnight_blue.json");
 *
 * STATUS (confirmed by repo-wide grep, 2026-07-14): this module has zero
 * importers anywhere else in src/ or server/ today — nothing in the editor,
 * the story-share API pipeline, or batchExport currently calls
 * getLocalStyle()/LOCAL_STYLES. It is kept because CLAUDE.md documents it as
 * an intentional public library surface for external consumers (statically
 * serving these files, or importing this package from another project) —
 * NOT because anything here depends on it. If that's no longer the intent,
 * this whole directory + `npm run styles:generate` can be deleted safely.
 */

import type { StyleSpecification } from "maplibre-gl";

import midnight_blue   from "./midnight_blue.json";
import terracotta      from "./terracotta.json";
import neon            from "./neon.json";
import coral           from "./coral.json";
import heatwave        from "./heatwave.json";
import ruby            from "./ruby.json";
import sage            from "./sage.json";
import copper          from "./copper.json";
import rustic          from "./rustic.json";
import blueprint       from "./blueprint.json";
import contrast_zones  from "./contrast_zones.json";
import copper_patina   from "./copper_patina.json";
import emerald         from "./emerald.json";
import forest          from "./forest.json";
import japanese_ink    from "./japanese_ink.json";
import noir            from "./noir.json";
import ocean           from "./ocean.json";
import pastel_dream    from "./pastel_dream.json";

export const LOCAL_STYLES: Record<string, StyleSpecification> = {
  midnight_blue:  midnight_blue  as unknown as StyleSpecification,
  terracotta:     terracotta     as unknown as StyleSpecification,
  neon:           neon           as unknown as StyleSpecification,
  coral:          coral          as unknown as StyleSpecification,
  heatwave:       heatwave       as unknown as StyleSpecification,
  ruby:           ruby           as unknown as StyleSpecification,
  sage:           sage           as unknown as StyleSpecification,
  copper:         copper         as unknown as StyleSpecification,
  rustic:         rustic         as unknown as StyleSpecification,
  blueprint:      blueprint      as unknown as StyleSpecification,
  contrast_zones: contrast_zones as unknown as StyleSpecification,
  copper_patina:  copper_patina  as unknown as StyleSpecification,
  emerald:        emerald        as unknown as StyleSpecification,
  forest:         forest         as unknown as StyleSpecification,
  japanese_ink:   japanese_ink   as unknown as StyleSpecification,
  noir:           noir           as unknown as StyleSpecification,
  ocean:          ocean          as unknown as StyleSpecification,
  pastel_dream:   pastel_dream   as unknown as StyleSpecification,
};

/** Returns the pre-baked style for a theme ID, or undefined if not found. */
export function getLocalStyle(themeId: string): StyleSpecification | undefined {
  return LOCAL_STYLES[themeId];
}
